language: node_js # node环境
node_js:
  - lts/*
services:
  - docker
script:
  - yarn build
before_deploy:
  - version = $(git rev-parse --short HEAD)
  - docker build -t zjhl2/algorigame:latest . -t zjhl2/algorigame:$version
  - docker run -p 8080:80 -d -P --rm zjhl2/algorigame:latest
  - docker ps -a
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zjhl2/algorigame:latest
  - docker push docker.io/zjhl2/algorigame:$version
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
    local_dir: dist